import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const isLoggedIn = true // 로그인 분기처리

  return (
    <html lang="en">
      {isLoggedIn ?
      <body className={`${inter.className} 
      mx-auto h-screen flex flex-col items-center 
      md:max-w-[120rem]`}
      >
      {children}
      </body>
      :
      <></> // <InitPage/> 로그인하지 않은 유저 보여줄 초기화면
      }
    </html>
  )
}
