import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BotNavBar from "./_commons/nav/BotNavBar";
import TopNavBar from "./_commons/nav/TopNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} 
      mx-auto w-full h-full flex flex-col items-center mt-24 mb-20 
      md:max-w-7xl md:w-4/5`}
      >
        <TopNavBar />
        {children}
        <BotNavBar />
      </body>
    </html>
  );
}
