import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} 
      mx-auto w-full h-screen flex flex-col items-center 
      md:max-w-7xl`}
      >
      {children}
      <footer className="
      fixed bottom-0 w-full bg-orange-300
      md:max-w-7xl
      ">
        bottom navBar here
      </footer>
      </body>
    </html>
  )
}
